# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'RecorderAndPlayerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RecorderAndPlayerDemo
	pod 'AFNetworking', '~> 3.1.0'
  target 'RecorderAndPlayerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RecorderAndPlayerDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
